# Makefile generated by gnetlist -g makefile.
# To adjust the contents of this header, edit the value attribute of the
# makefile-prolog symbol in Makefile.sch using gschem.

# A place to adjust pathnames and options of tools

GSCHEM=gschem
GNETLIST=gnetlist -L .

# Default rule

all : all-products

# Rule to remake the Makefile

Makefile : Makefile.sch
	echo '(hierarchy-traversal "disabled")' >gnetlistrc
	$(GNETLIST) -g makefile -o Makefile Makefile.sch

# Command C1

.PHONY : all-products
all-products : example.net example.parts.txt 

# Rule R1

example.1.sch  : 
	$(GSCHEM) $@

# Rule R2

example.2.sch  : 
	$(GSCHEM) $@

# Rule R3

example.net  : example.1.sch example.2.sch 
	rm -f gnetlistrc
	$(GNETLIST) -g osmond -o $@ $^

# Rule R4

example.parts.txt  : example.1.sch example.2.sch 
	rm -f gnetlistrc
	$(GNETLIST) -g partslist1 -o $@ $^

